vich_uploader:
    mappings:
        taxes:
            uri_prefix: /files/taxes
            upload_destination: '%kernel.project_dir%/public/files/taxes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
